## Pandas and Numpy

In [1]:
import pandas as pd
import numpy as np

In [2]:
orders = [
    {"order_id": "ORD001", "customer_id": "C100", "city": "New York", "state": "NY", "zip": "10001", "status": "delivered", "delivery_cost": 12.99, "freight": 4.50, "order_value": 89.99, "days_late": 2, "courier": "FedEx", "category": "Electronics", "weight_kg": 1.2},
    {"order_id": "ORD002", "customer_id": "C101", "city": "Los Angeles", "state": "CA", "zip": "90001", "status": "delivered", "delivery_cost": 15.99, "freight": 6.20, "order_value": 124.99, "days_late": 0, "courier": "UPS", "category": "Clothing", "weight_kg": 0.8},
    {"order_id": "ORD003", "customer_id": "C102", "city": "Chicago", "state": "IL", "zip": "60601", "status": "cancelled", "delivery_cost": 0.00, "freight": 0.00, "order_value": 0.00, "days_late": 0, "courier": "USPS", "category": "Books", "weight_kg": 0.5},
    {"order_id": "ORD004", "customer_id": "C103", "city": "Houston", "state": "TX", "zip": "77001", "status": "delivered", "delivery_cost": 18.50, "freight": 7.80, "order_value": 199.99, "days_late": 5, "courier": "FedEx", "category": "Electronics", "weight_kg": 3.5},
    {"order_id": "ORD005", "customer_id": "C104", "city": "Phoenix", "state": "AZ", "zip": "85001", "status": "delivered", "delivery_cost": 11.25, "freight": 3.90, "order_value": 45.99, "days_late": -1, "courier": "UPS", "category": "Home & Garden", "weight_kg": 2.1},
    {"order_id": "ORD006", "customer_id": "C105", "city": "Philadelphia", "state": "PA", "zip": "19101", "status": "delivered", "delivery_cost": 9.99, "freight": 3.20, "order_value": 34.99, "days_late": 0, "courier": "USPS", "category": "Books", "weight_kg": 0.4},
    {"order_id": "ORD007", "customer_id": "C106", "city": "San Antonio", "state": "TX", "zip": "78201", "status": "delivered", "delivery_cost": 22.75, "freight": 9.10, "order_value": 299.99, "days_late": 8, "courier": "FedEx", "category": "Electronics", "weight_kg": 4.2},
    {"order_id": "ORD008", "customer_id": "C107", "city": "San Diego", "state": "CA", "zip": "92101", "status": "delivered", "delivery_cost": 14.50, "freight": 5.60, "order_value": 89.99, "days_late": -2, "courier": "UPS", "category": "Clothing", "weight_kg": 0.6},
    {"order_id": "ORD009", "customer_id": "C108", "city": "Dallas", "state": "TX", "zip": "75201", "status": "cancelled", "delivery_cost": 0.00, "freight": 0.00, "order_value": 0.00, "days_late": 0, "courier": "USPS", "category": "Sports", "weight_kg": 1.8},
    {"order_id": "ORD010", "customer_id": "C109", "city": "San Jose", "state": "CA", "zip": "95101", "status": "delivered", "delivery_cost": 16.75, "freight": 6.80, "order_value": 149.99, "days_late": 3, "courier": "FedEx", "category": "Electronics", "weight_kg": 2.3},
    {"order_id": "ORD011", "customer_id": "C110", "city": "Austin", "state": "TX", "zip": "78701", "status": "delivered", "delivery_cost": 13.25, "freight": 4.90, "order_value": 79.99, "days_late": 0, "courier": "UPS", "category": "Home & Garden", "weight_kg": 1.5},
    {"order_id": "ORD012", "customer_id": "C111", "city": "Jacksonville", "state": "FL", "zip": "32201", "status": "delivered", "delivery_cost": 19.99, "freight": 8.20, "order_value": 224.99, "days_late": 6, "courier": "FedEx", "category": "Electronics", "weight_kg": 3.8},
    {"order_id": "ORD013", "customer_id": "C112", "city": "Fort Worth", "state": "TX", "zip": "76101", "status": "delivered", "delivery_cost": 8.75, "freight": 2.80, "order_value": 29.99, "days_late": -3, "courier": "USPS", "category": "Books", "weight_kg": 0.3},
    {"order_id": "ORD014", "customer_id": "C113", "city": "Columbus", "state": "OH", "zip": "43201", "status": "delivered", "delivery_cost": 17.50, "freight": 7.20, "order_value": 174.99, "days_late": 4, "courier": "UPS", "category": "Sports", "weight_kg": 2.8},
    {"order_id": "ORD015", "customer_id": "C114", "city": "Charlotte", "state": "NC", "zip": "28201", "status": "cancelled", "delivery_cost": 0.00, "freight": 0.00, "order_value": 0.00, "days_late": 0, "courier": "FedEx", "category": "Clothing", "weight_kg": 0.7},
    {"order_id": "ORD016", "customer_id": "C115", "city": "Indianapolis", "state": "IN", "zip": "46201", "status": "delivered", "delivery_cost": 10.50, "freight": 3.60, "order_value": 54.99, "days_late": 1, "courier": "USPS", "category": "Books", "weight_kg": 0.5},
    {"order_id": "ORD017", "customer_id": "C116", "city": "San Francisco", "state": "CA", "zip": "94101", "status": "delivered", "delivery_cost": 21.99, "freight": 8.90, "order_value": 274.99, "days_late": 7, "courier": "FedEx", "category": "Electronics", "weight_kg": 3.2},
    {"order_id": "ORD018", "customer_id": "C117", "city": "Seattle", "state": "WA", "zip": "98101", "status": "delivered", "delivery_cost": 12.25, "freight": 4.30, "order_value": 69.99, "days_late": 0, "courier": "UPS", "category": "Home & Garden", "weight_kg": 1.9},
    {"order_id": "ORD019", "customer_id": "C118", "city": "Denver", "state": "CO", "zip": "80201", "status": "delivered", "delivery_cost": 24.99, "freight": 10.50, "order_value": 349.99, "days_late": 9, "courier": "FedEx", "category": "Electronics", "weight_kg": 5.1},
    {"order_id": "ORD020", "customer_id": "C119", "city": "Nashville", "state": "TN", "zip": "37201", "status": "delivered", "delivery_cost": 9.50, "freight": 3.10, "order_value": 39.99, "days_late": -1, "courier": "USPS", "category": "Clothing", "weight_kg": 0.4},
    {"order_id": "ORD021", "customer_id": "C120", "city": "Oklahoma City", "state": "OK", "zip": "73101", "status": "delivered", "delivery_cost": 16.25, "freight": 6.50, "order_value": 134.99, "days_late": 3, "courier": "UPS", "category": "Sports", "weight_kg": 2.4},
    {"order_id": "ORD022", "customer_id": "C121", "city": "El Paso", "state": "TX", "zip": "79901", "status": "cancelled", "delivery_cost": 0.00, "freight": 0.00, "order_value": 0.00, "days_late": 0, "courier": "FedEx", "category": "Electronics", "weight_kg": 2.9},
    {"order_id": "ORD023", "customer_id": "C122", "city": "Boston", "state": "MA", "zip": "02101", "status": "delivered", "delivery_cost": 20.75, "freight": 8.60, "order_value": 249.99, "days_late": 5, "courier": "FedEx", "category": "Electronics", "weight_kg": 3.6},
    {"order_id": "ORD024", "customer_id": "C123", "city": "Portland", "state": "OR", "zip": "97201", "status": "delivered", "delivery_cost": 11.75, "freight": 4.10, "order_value": 64.99, "days_late": 0, "courier": "UPS", "category": "Books", "weight_kg": 0.6},
    {"order_id": "ORD025", "customer_id": "C124", "city": "Las Vegas", "state": "NV", "zip": "89101", "status": "delivered", "delivery_cost": 18.99, "freight": 7.90, "order_value": 214.99, "days_late": 6, "courier": "FedEx", "category": "Home & Garden", "weight_kg": 4.0},
    {"order_id": "ORD026", "customer_id": "C125", "city": "Memphis", "state": "TN", "zip": "38101", "status": "delivered", "delivery_cost": 8.25, "freight": 2.60, "order_value": 24.99, "days_late": -2, "courier": "USPS", "category": "Clothing", "weight_kg": 0.3},
    {"order_id": "ORD027", "customer_id": "C126", "city": "Louisville", "state": "KY", "zip": "40201", "status": "delivered", "delivery_cost": 15.50, "freight": 6.00, "order_value": 114.99, "days_late": 2, "courier": "UPS", "category": "Sports", "weight_kg": 2.0},
    {"order_id": "ORD028", "customer_id": "C127", "city": "Baltimore", "state": "MD", "zip": "21201", "status": "cancelled", "delivery_cost": 0.00, "freight": 0.00, "order_value": 0.00, "days_late": 0, "courier": "FedEx", "category": "Books", "weight_kg": 0.5},
    {"order_id": "ORD029", "customer_id": "C128", "city": "Milwaukee", "state": "WI", "zip": "53201", "status": "delivered", "delivery_cost": 23.50, "freight": 9.80, "order_value": 324.99, "days_late": 10, "courier": "FedEx", "category": "Electronics", "weight_kg": 4.8},
    {"order_id": "ORD030", "customer_id": "C129", "city": "Albuquerque", "state": "NM", "zip": "87101", "status": "delivered", "delivery_cost": 13.75, "freight": 5.20, "order_value": 94.99, "days_late": 1, "courier": "UPS", "category": "Home & Garden", "weight_kg": 1.7},
    {"order_id": "ORD031", "customer_id": "C130", "city": "Tucson", "state": "AZ", "zip": "85701", "status": "delivered", "delivery_cost": 10.25, "freight": 3.50, "order_value": 49.99, "days_late": 0, "courier": "USPS", "category": "Clothing", "weight_kg": 0.5},
    {"order_id": "ORD032", "customer_id": "C131", "city": "Fresno", "state": "CA", "zip": "93701", "status": "delivered", "delivery_cost": 19.25, "freight": 7.80, "order_value": 204.99, "days_late": 4, "courier": "FedEx", "category": "Electronics", "weight_kg": 3.3},
    {"order_id": "ORD033", "customer_id": "C132", "city": "Sacramento", "state": "CA", "zip": "95801", "status": "delivered", "delivery_cost": 14.99, "freight": 5.80, "order_value": 109.99, "days_late": -1, "courier": "UPS", "category": "Sports", "weight_kg": 1.6},
    {"order_id": "ORD034", "customer_id": "C133", "city": "Kansas City", "state": "MO", "zip": "64101", "status": "cancelled", "delivery_cost": 0.00, "freight": 0.00, "order_value": 0.00, "days_late": 0, "courier": "USPS", "category": "Home & Garden", "weight_kg": 2.2},
    {"order_id": "ORD035", "customer_id": "C134", "city": "Atlanta", "state": "GA", "zip": "30301", "status": "delivered", "delivery_cost": 17.25, "freight": 7.00, "order_value": 164.99, "days_late": 3, "courier": "FedEx", "category": "Electronics", "weight_kg": 2.7},
    {"order_id": "ORD036", "customer_id": "C135", "city": "Miami", "state": "FL", "zip": "33101", "status": "delivered", "delivery_cost": 11.50, "freight": 4.00, "order_value": 59.99, "days_late": 0, "courier": "UPS", "category": "Clothing", "weight_kg": 0.7},
    {"order_id": "ORD037", "customer_id": "C136", "city": "Raleigh", "state": "NC", "zip": "27601", "status": "delivered", "delivery_cost": 25.99, "freight": 11.20, "order_value": 399.99, "days_late": 11, "courier": "FedEx", "category": "Electronics", "weight_kg": 5.5},
    {"order_id": "ORD038", "customer_id": "C137", "city": "Omaha", "state": "NE", "zip": "68101", "status": "delivered", "delivery_cost": 9.25, "freight": 3.00, "order_value": 34.99, "days_late": -3, "courier": "USPS", "category": "Books", "weight_kg": 0.4},
    {"order_id": "ORD039", "customer_id": "C138", "city": "Cleveland", "state": "OH", "zip": "44101", "status": "delivered", "delivery_cost": 16.50, "freight": 6.60, "order_value": 139.99, "days_late": 2, "courier": "UPS", "category": "Sports", "weight_kg": 2.5},
    {"order_id": "ORD040", "customer_id": "C139", "city": "New Orleans", "state": "LA", "zip": "70101", "status": "cancelled", "delivery_cost": 0.00, "freight": 0.00, "order_value": 0.00, "days_late": 0, "courier": "FedEx", "category": "Electronics", "weight_kg": 3.1},
]

In [3]:
df = pd.DataFrame(orders)
df.describe(include="all")

,order_id,customer_id,city,state,zip,status,delivery_cost,freight,order_value,days_late,courier,category,weight_kg
count,40,40,40,40,40,40,40.000000,40.000000,40.000000,40.000000,40,40,40.000000
unique,40,40,40,25,40,2,NaN,NaN,NaN,NaN,3,5,NaN
top,ORD001,C100,New York,CA,10001,delivered,NaN,NaN,NaN,NaN,FedEx,Electronics,NaN
freq,1,1,1,6,1,33,NaN,NaN,NaN,NaN,17,14,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,12.879000,5.005000,118.141750,1.975000,NaN,NaN,2.072500
std,NaN,NaN,NaN,NaN,NaN,NaN,7.492942,3.185862,107.824948,3.519087,NaN,NaN,1.481508
min,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,-3.000000,NaN,NaN,0.300000
25%,NaN,NaN,NaN,NaN,NaN,NaN,9.437500,3.075000,34.990000,0.000000,NaN,NaN,0.600000
50%,NaN,NaN,NaN,NaN,NaN,NaN,13.500000,5.050000,89.990000,0.000000,NaN,NaN,1.950000
75%,NaN,NaN,NaN,NaN,NaN,NaN,17.750000,7.350000,181.240000,4.000000,NaN,NaN,3.125000
max,NaN,NaN,NaN,NaN,NaN,NaN,25.990000,11.200000,399.990000,11.000000,NaN,NaN,5.500000

## Flag, new columns for alerts

In [4]:
df["delivery_status"] = np.where(
        df["days_late"] > 0, "Late", 
        np.where(df["days_late"] == 0, "On Time", "Early"))

In [5]:
df["delivery_status"].value_counts()

delivery_status
Late       19
On Time    14
Early       7
Name: count, dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         40 non-null     object
 1   customer_id      40 non-null     object
 2   city             40 non-null     object
 3   state            40 non-null     object
 4   zip              40 non-null     object
 5   status           40 non-null     object
 6   delivery_cost    40 non-null     float64
 7   freight          40 non-null     float64
 8   order_value      40 non-null     float64
 9   days_late        40 non-null     int64
 10  courier          40 non-null     object
 11  category         40 non-null     object
 12  weight_kg        40 non-null     float64
 13  delivery_status  40 non-null     object
dtypes: float64(4), int64(1), object(9)
memory usage: 4.5+ KB

In [7]:
df["freight_ratio"] = round((df["freight"]/ df["order_value"]) * 100, 2)

In [8]:
df["freight_ratio"] = round((df["freight"]/ df["order_value"].replace(0, np.nan)) * 100,2)

In [9]:
df[["order_id", "status", "freight_ratio"]].head(10)

  order_id     status  freight_ratio
0   ORD001  delivered           5.00
1   ORD002  delivered           4.96
2   ORD003  cancelled            NaN
3   ORD004  delivered           3.90
4   ORD005  delivered           8.48
5   ORD006  delivered           9.15
6   ORD007  delivered           3.03
7   ORD008  delivered           6.22
8   ORD009  cancelled            NaN
9   ORD010  delivered           4.53

In [10]:
df["freight_ratio"] = df["freight_ratio"].fillna(0)
df[["freight_ratio", "status", "order_id"]].head(10)

   freight_ratio     status order_id
0           5.00  delivered   ORD001
1           4.96  delivered   ORD002
2           0.00  cancelled   ORD003
3           3.90  delivered   ORD004
4           8.48  delivered   ORD005
5           9.15  delivered   ORD006
6           3.03  delivered   ORD007
7           6.22  delivered   ORD008
8           0.00  cancelled   ORD009
9           4.53  delivered   ORD010

In [11]:
df[["order_id", "city", "status", "days_late", "delivery_status", "freight_ratio"]].head(10)

  order_id          city     status  days_late delivery_status  freight_ratio
0   ORD001      New York  delivered          2            Late           5.00
1   ORD002   Los Angeles  delivered          0         On Time           4.96
2   ORD003       Chicago  cancelled          0         On Time           0.00
3   ORD004       Houston  delivered          5            Late           3.90
4   ORD005       Phoenix  delivered         -1           Early           8.48
5   ORD006  Philadelphia  delivered          0         On Time           9.15
6   ORD007   San Antonio  delivered          8            Late           3.03
7   ORD008     San Diego  delivered         -2           Early           6.22
8   ORD009        Dallas  cancelled          0         On Time           0.00
9   ORD010      San Jose  delivered          3            Late           4.53

In [12]:
df.groupby("city")["delivery_cost"].mean().round(2).sort_values(ascending=False)

city
Raleigh          25.99
Denver           24.99
Milwaukee        23.50
San Antonio      22.75
San Francisco    21.99
Boston           20.75
Jacksonville     19.99
Fresno           19.25
Las Vegas        18.99
Houston          18.50
Columbus         17.50
Atlanta          17.25
San Jose         16.75
Cleveland        16.50
Oklahoma City    16.25
Los Angeles      15.99
Louisville       15.50
Sacramento       14.99
San Diego        14.50
Albuquerque      13.75
Austin           13.25
New York         12.99
Seattle          12.25
Portland         11.75
Miami            11.50
Phoenix          11.25
Indianapolis     10.50
Tucson           10.25
Philadelphia      9.99
Nashville         9.50
Omaha             9.25
Fort Worth        8.75
Memphis           8.25
Chicago           0.00
Baltimore         0.00
Charlotte         0.00
Kansas City       0.00
Dallas            0.00
El Paso           0.00
New Orleans       0.00
Name: delivery_cost, dtype: float64

1. Average days_late by courier — which courier is worst?

In [13]:
df.groupby("courier")["days_late"].mean().round().sort_values(ascending=False)

courier
FedEx    5.0
UPS      1.0
USPS    -1.0
Name: days_late, dtype: float64

2. Total order_value by state — which state generates most revenue?

In [14]:
df.groupby("state")["order_value"].sum().sort_values(ascending=False)

state
CA    954.94
TX    609.96
NC    399.99
CO    349.99
WI    324.99
OH    314.98
FL    284.98
MA    249.99
NV    214.99
GA    164.99
OK    134.99
KY    114.99
AZ     95.98
NM     94.99
NY     89.99
WA     69.99
OR     64.99
TN     64.98
IN     54.99
NE     34.99
PA     34.99
LA      0.00
IL      0.00
MD      0.00
MO      0.00
Name: order_value, dtype: float64

3. Count of orders by delivery_status — you already did this with value_counts() but try it with groupby this time using .count()

In [15]:
df.columns

Index(['order_id', 'customer_id', 'city', 'state', 'zip', 'status',
       'delivery_cost', 'freight', 'order_value', 'days_late', 'courier',
       'category', 'weight_kg', 'delivery_status', 'freight_ratio'],
      dtype='object')

In [16]:
df.groupby("delivery_status")["order_id"].count()

delivery_status
Early       7
Late       19
On Time    14
Name: order_id, dtype: int64

In [17]:
df.groupby(["state", "courier"])["days_late"].mean().round(2).sort_values(ascending=False)

state  courier
WI     FedEx      10.00
CO     FedEx       9.00
NV     FedEx       6.00
FL     FedEx       6.00
NC     FedEx       5.50
MA     FedEx       5.00
CA     FedEx       4.67
TX     FedEx       4.33
OK     UPS         3.00
OH     UPS         3.00
GA     FedEx       3.00
NY     FedEx       2.00
KY     UPS         2.00
IN     USPS        1.00
NM     UPS         1.00
WA     UPS         0.00
MD     FedEx       0.00
MO     USPS        0.00
FL     UPS         0.00
AZ     USPS        0.00
IL     USPS        0.00
LA     FedEx       0.00
TX     UPS         0.00
OR     UPS         0.00
PA     USPS        0.00
CA     UPS        -1.00
AZ     UPS        -1.00
TN     USPS       -1.50
TX     USPS       -1.50
NE     USPS       -3.00
Name: days_late, dtype: float64

In [18]:
df.groupby("courier").agg(
    total_orders = ("order_id", "count"),
    avg_days_late = ("days_late", "mean"),
    late_count = ("days_late", lambda x: (x > 0).sum()),
).round(2)

         total_orders  avg_days_late  late_count
courier
FedEx              17           4.65          13
UPS                13           0.62           5
USPS               10          -0.80           1

In [19]:
df["cost_category"] = np.where(df["delivery_cost"] > 20, "High",
                    np.where(df["delivery_cost"] > 10, "Medium", "Low")
    )

In [20]:
df[["order_id", "delivery_cost", "cost_category"]].head(20)

   order_id  delivery_cost cost_category
0    ORD001          12.99        Medium
1    ORD002          15.99        Medium
2    ORD003           0.00           Low
3    ORD004          18.50        Medium
4    ORD005          11.25        Medium
5    ORD006           9.99           Low
6    ORD007          22.75          High
7    ORD008          14.50        Medium
8    ORD009           0.00           Low
9    ORD010          16.75        Medium
10   ORD011          13.25        Medium
11   ORD012          19.99        Medium
12   ORD013           8.75           Low
13   ORD014          17.50        Medium
14   ORD015           0.00           Low
15   ORD016          10.50        Medium
16   ORD017          21.99          High
17   ORD018          12.25        Medium
18   ORD019          24.99          High
19   ORD020           9.50           Low

In [21]:
df.columns

Index(['order_id', 'customer_id', 'city', 'state', 'zip', 'status',
       'delivery_cost', 'freight', 'order_value', 'days_late', 'courier',
       'category', 'weight_kg', 'delivery_status', 'freight_ratio',
       'cost_category'],
      dtype='object')

In [24]:
df["breach_severity"] = np.where(df["days_late"] > 7, "Critical",
                  np.where(df["days_late"] > 3, "Moderate",
                  np.where(df["days_late"] > 0, "Minor", "None")))

In [27]:
df[["order_id", "status", "breach_severity"]].head(20)

   order_id     status breach_severity
0    ORD001  delivered           Minor
1    ORD002  delivered            None
2    ORD003  cancelled            None
3    ORD004  delivered        Moderate
4    ORD005  delivered            None
5    ORD006  delivered            None
6    ORD007  delivered        Critical
7    ORD008  delivered            None
8    ORD009  cancelled            None
9    ORD010  delivered           Minor
10   ORD011  delivered            None
11   ORD012  delivered        Moderate
12   ORD013  delivered            None
13   ORD014  delivered        Moderate
14   ORD015  cancelled            None
15   ORD016  delivered           Minor
16   ORD017  delivered        Moderate
17   ORD018  delivered            None
18   ORD019  delivered        Critical
19   ORD020  delivered            None

In [28]:
df["breach_severity"].value_counts()

breach_severity
None        21
Minor        8
Moderate     7
Critical     4
Name: count, dtype: int64

In [31]:
df["region"] = np.where(df["state"].isin(["CA", "OR", "WA"]), "West",
                np.where(df["state"].isin(["NY", "MA", "PA", "MD"]), "Northeast", 
                np.where(df["state"].isin(["TX", "FL", "GA", "NC", "TN", "LA"]), "South", "Midwest" 
)))

In [33]:
df["region"].value_counts()

region
South        14
Midwest      14
West          8
Northeast     4
Name: count, dtype: int64

In [35]:
double = lambda x: x * 2
print(double(5))

10

In [39]:
price = lambda x: x + (x * 0.085)
print(price(25))

27.125

In [43]:
df["order_value_with_tax"] = df["order_value"].apply(lambda x: round(x + (x * 0.085),2))
df[["order_id", "order_value", "order_value_with_tax"]].head(20)

   order_id  order_value  order_value_with_tax
0    ORD001        89.99                 97.64
1    ORD002       124.99                135.61
2    ORD003         0.00                  0.00
3    ORD004       199.99                216.99
4    ORD005        45.99                 49.90
5    ORD006        34.99                 37.96
6    ORD007       299.99                325.49
7    ORD008        89.99                 97.64
8    ORD009         0.00                  0.00
9    ORD010       149.99                162.74
10   ORD011        79.99                 86.79
11   ORD012       224.99                244.11
12   ORD013        29.99                 32.54
13   ORD014       174.99                189.86
14   ORD015         0.00                  0.00
15   ORD016        54.99                 59.66
16   ORD017       274.99                298.36
17   ORD018        69.99                 75.94
18   ORD019       349.99                379.74
19   ORD020        39.99                 43.39

In [46]:
df["delivery_cost_per_kilogram"] = df.apply(lambda row: round(row["delivery_cost"] / row["weight_kg"],2), axis=1)

In [47]:
df.columns

Index(['order_id', 'customer_id', 'city', 'state', 'zip', 'status',
       'delivery_cost', 'freight', 'order_value', 'days_late', 'courier',
       'category', 'weight_kg', 'delivery_status', 'freight_ratio',
       'cost_category', 'breach_severity', 'region', 'order_value_with_tax',
       'delivery_cost_per_kilogram'],
      dtype='object')

In [50]:
df[["order_id", "delivery_cost", "weight_kg",  "delivery_cost_per_kilogram", "status"]].head(20)

   order_id  delivery_cost  weight_kg  delivery_cost_per_kilogram     status
0    ORD001          12.99        1.2                       10.83  delivered
1    ORD002          15.99        0.8                       19.99  delivered
2    ORD003           0.00        0.5                        0.00  cancelled
3    ORD004          18.50        3.5                        5.29  delivered
4    ORD005          11.25        2.1                        5.36  delivered
5    ORD006           9.99        0.4                       24.97  delivered
6    ORD007          22.75        4.2                        5.42  delivered
7    ORD008          14.50        0.6                       24.17  delivered
8    ORD009           0.00        1.8                        0.00  cancelled
9    ORD010          16.75        2.3                        7.28  delivered
10   ORD011          13.25        1.5                        8.83  delivered
11   ORD012          19.99        3.8                        5.26  delivered
12   ORD013           8.75        0.3                       29.17  delivered
13   ORD014          17.50        2.8                        6.25  delivered
14   ORD015           0.00        0.7                        0.00  cancelled
15   ORD016          10.50        0.5                       21.00  delivered
16   ORD017          21.99        3.2                        6.87  delivered
17   ORD018          12.25        1.9                        6.45  delivered
18   ORD019          24.99        5.1                        4.90  delivered
19   ORD020           9.50        0.4                       23.75  delivered

In [51]:
df[df["status"] == "cancelled"][["order_id", "delivery_cost", "weight_kg",  "delivery_cost_per_kilogram", "status"]]

   order_id  delivery_cost  weight_kg  delivery_cost_per_kilogram     status
2    ORD003            0.0        0.5                         0.0  cancelled
8    ORD009            0.0        1.8                         0.0  cancelled
14   ORD015            0.0        0.7                         0.0  cancelled
21   ORD022            0.0        2.9                         0.0  cancelled
27   ORD028            0.0        0.5                         0.0  cancelled
33   ORD034            0.0        2.2                         0.0  cancelled
39   ORD040            0.0        3.1                         0.0  cancelled

In [59]:
df.groupby("region").agg(
    total_orders = ("order_id", "count"),
    avg_delivery_cost = ("delivery_cost", "mean"),
    avg_days_late = ("days_late", "mean"),
    late_orders = ("days_late", lambda x: (x > 0).sum()),
    total_revenue = ("order_value", "sum"),
    courier = ("courier", "max")
).round(2).sort_values("avg_days_late", ascending=False)

,total_orders,avg_delivery_cost,avg_days_late,late_orders,total_revenue,courier
region,,,,,,
Midwest,14,13.44,2.43,9,1735.88,USPS
South,14,11.12,1.93,5,1524.90,USPS
Northeast,4,10.93,1.75,2,374.97,USPS
West,8,15.93,1.38,3,1089.92,UPS

In [ ]:
df[df["region"].isin(["Midwest","South",])].groupby("courier").agg(
    total_orders = ("order_id", "count"),
    avg_days_late = ("days_late", "mean"),
    late_orders = ("days_late", lambda x: (x > 0).sum())
).round(2).sort_values("avg_days_late", ascending=False)

         total_orders  avg_days_late  late_orders
courier
FedEx              17           4.65           13
UPS                13           0.62            5
USPS               10          -0.80            1

In [68]:
df[df["region"].isin(["Northeast","West",])].groupby("courier").agg(
    total_orders = ("order_id", "count"),
    avg_days_late = ("days_late", "mean"),
    late_orders = ("days_late", lambda x: (x > 0).sum())
).round(2).sort_values("avg_days_late", ascending=False)

         total_orders  avg_days_late  late_orders
courier
FedEx               6            3.5            5
USPS                1            0.0            0
UPS                 5           -0.6            0

## export to excel

In [69]:
summary = df.groupby(["region", "courier"]).agg(
    total_orders = ("order_id", "count"),
    avg_days_late = ("days_late", "mean"),
    late_orders = ("days_late", lambda x: (x > 0).sum()),
    total_revenue = ("order_value", "sum")
).round(2).reset_index()

In [70]:
summary.to_excel("courier_performance_report.xlsx", index=False)